from pathlib import Path

PYDANTIC_TO_PASTE_SOURCE = Path(
    "src/detours/detour_ai_augment/src/backend/helpers/data_models/pydantic_to_paste.py"
).read_text(encoding="utf-8").rstrip()

AI_AUGMENT_COLUMN_PREFIX = "ktp.ai_augment_"

KTP_AI_AUGMENT_RESEARCHER_AUTHOR_COL = f"{AI_AUGMENT_COLUMN_PREFIX}researcher_author"
KTP_AI_AUGMENT_PLACE_OF_RESIDENCE_COL = f"{AI_AUGMENT_COLUMN_PREFIX}place_of_residence"
KTP_AI_AUGMENT_RACE_ETHNICITY_LANGUAGE_CULTURE_COL = (
    f"{AI_AUGMENT_COLUMN_PREFIX}race_ethnicity_language_culture"
)
KTP_AI_AUGMENT_GENDER_COL = f"{AI_AUGMENT_COLUMN_PREFIX}gender"
KTP_AI_AUGMENT_AGE_FIRST_PUBLICATION_COL = (
    f"{AI_AUGMENT_COLUMN_PREFIX}age_first_publication_according_to_openalex_profile"
)
KTP_AI_AUGMENT_EDUCATION_COL = f"{AI_AUGMENT_COLUMN_PREFIX}education"
KTP_AI_AUGMENT_ACADEMIC_POSITIONS_COL = f"{AI_AUGMENT_COLUMN_PREFIX}academic_position_s_"
KTP_AI_AUGMENT_SOCIAL_CAPITAL_COL = f"{AI_AUGMENT_COLUMN_PREFIX}social_capital"
KTP_AI_AUGMENT_LINKS_COL = f"{AI_AUGMENT_COLUMN_PREFIX}links_"
KTP_AI_AUGMENT_COMMENTS_COL = f"{AI_AUGMENT_COLUMN_PREFIX}comments"
AI_AUGMENT_EVIDENCE_COLUMNS = (
    KTP_AI_AUGMENT_RESEARCHER_AUTHOR_COL,
    KTP_AI_AUGMENT_PLACE_OF_RESIDENCE_COL,
    KTP_AI_AUGMENT_RACE_ETHNICITY_LANGUAGE_CULTURE_COL,
    KTP_AI_AUGMENT_GENDER_COL,
    KTP_AI_AUGMENT_AGE_FIRST_PUBLICATION_COL,
    KTP_AI_AUGMENT_EDUCATION_COL,
    KTP_AI_AUGMENT_ACADEMIC_POSITIONS_COL,
    KTP_AI_AUGMENT_SOCIAL_CAPITAL_COL,
    KTP_AI_AUGMENT_LINKS_COL,
)
AI_AUGMENT_COLUMNS = AI_AUGMENT_EVIDENCE_COLUMNS + (KTP_AI_AUGMENT_COMMENTS_COL,)
AI_AUGMENT_STANDARDIZED_SUFFIX = "_standardized"
AI_AUGMENT_STANDARDIZED_COLUMNS = tuple(
    f"{column}{AI_AUGMENT_STANDARDIZED_SUFFIX}"
    for column in AI_AUGMENT_EVIDENCE_COLUMNS
)
AI_AUGMENT_EVIDENCE_STANDARDIZED_PAIRS = tuple(
    zip(
        AI_AUGMENT_EVIDENCE_COLUMNS,
        AI_AUGMENT_STANDARDIZED_COLUMNS,
        strict=True,
    )
)

KTP_AI_AUGMENT_ATTEMPT_ID_COL = f"{AI_AUGMENT_COLUMN_PREFIX}attempt_id"
KTP_AI_AUGMENT_SESSION_METADATA_COL = f"{AI_AUGMENT_COLUMN_PREFIX}session_metadata"
KTP_AI_AUGMENT_FOOTNOTES_COL = f"{AI_AUGMENT_COLUMN_PREFIX}footnotes"
KTP_AI_AUGMENT_FOOTNOTE_ARGUMENTS_COL = f"{AI_AUGMENT_COLUMN_PREFIX}footnote_arguments"

TEXT_ENCODING = "utf-8"

CONFIG_FILENAME = "config_ai_augment.json"
MAP_SUBSET_0_TO_BATCH_KEY = "map_subset_0_to_batch"
REPLAY_LOG_KEY = "detour_ai_augment_backend_api_replay_log"
